# fly.toml app configuration file generated for graph-ql-pet-project on 2025-08-01T15:10:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'graph-ql-pet-project'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
